openapi: 3.0.0
info:
  version: 1.0.0
  title: example service
servers:
  - url: http://localhost:12000
paths:
  /example/{id}:
    get:
      description: create an item
      parameters: &parameters
        - in: path
          required: true
          name: id
          schema:
            type: string
        - in: query
          name: foo
          schema:
            type: string
      responses:
        '200':
          description: ok
          headers:
            location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    post:
      description: create an item
      parameters: *parameters
      requestBody:
        $ref: "#/components/requestBodies/PostBody"
      responses:
        '200':
          description: ok
          headers:
            location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
components:
  requestBodies:
    PostBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Item'
  schemas:
    Item:
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string

